package jm.task.core.jdbc.dao;

import jm.task.core.jdbc.model.User;
import jm.task.core.jdbc.util.Util;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class UserDaoJDBCImpl implements UserDao {
    private static final Logger logger = LoggerFactory.getLogger(UserDaoJDBCImpl.class);
    private final Util util = new Util();

    public void createUsersTable() {
        logger.debug("Creating users table using JDBC");

        String sql = "CREATE TABLE IF NOT EXISTS Users" +
                "(id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "name CHARACTER VARYING(30)," +
                "lastName CHARACTER VARYING(30)," +
                "age INTEGER)";
        connectAndExecute(sql);
    }

    public void dropUsersTable() {
        logger.debug("Dropping users table using JDBC");

        String sql = "DROP TABLE IF EXISTS Users";
        connectAndExecute(sql);
    }

    public void saveUser(String name, String lastName, byte age) {
        logger.debug("Saving user in table using JDBC");

        String sql = "INSERT INTO Users (name, lastName, age) VALUES (?, ?, ?)";
        if (name == null || lastName == null) {
            throw new NullPointerException("Saving user without name or last name using JDBC");
        }
        try (Connection connection = util.getConnection(); PreparedStatement preparedStatement = connection.prepareStatement(sql)) {
            preparedStatement.setString(1, name);
            preparedStatement.setString(2, lastName);
            preparedStatement.setByte(3, age);

            preparedStatement.executeUpdate();
        } catch (SQLException | ClassNotFoundException e) {
            throw new RuntimeException("Exception during removing user by id using JDBC", e);
        }
    }

    public void removeUserById(long id) {
        logger.debug("Removing user from table by id using JDBC");

        String sql = "DELETE FROM Users WHERE id = ?";
        try (Connection connection = util.getConnection(); PreparedStatement preparedStatement = connection.prepareStatement(sql)) {
            preparedStatement.setLong(1, id);

            preparedStatement.executeUpdate();
        } catch (SQLException | ClassNotFoundException e) {
            throw new RuntimeException("Exception during removing user by id using JDBC", e);
        }
    }

    public void cleanUsersTable() {
        logger.debug("Cleaning users table using JDBC");

        String sql = "DELETE FROM Users";
        connectAndExecute(sql);
    }

    public List<User> getAllUsers() {
        logger.debug("Get all users from table using JDBC");

        String sql = "SELECT id, name, lastName, age FROM Users";
        List<User> users = new ArrayList<>();
        try (Connection connection = util.getConnection(); Statement statement = connection.createStatement()) {
            ResultSet resultSet = statement.executeQuery(sql);

            while (resultSet.next()) {
                User user = new User();
                user.setId(resultSet.getLong("id"));
                user.setName(resultSet.getString("name"));
                user.setLastName(resultSet.getString("lastName"));
                user.setAge(resultSet.getByte("age"));

                users.add(user);
            }

            return users;
        } catch (SQLException | ClassNotFoundException e) {
            throw new RuntimeException("Exception during getting list of all users using JDBC", e);
        }
    }

    private void connectAndExecute(String sql) {
        try (Connection connection = util.getConnection(); Statement statement = connection.createStatement()) {
            statement.executeUpdate(sql);
        } catch (SQLException | ClassNotFoundException e) {
            throw new RuntimeException("Exception when not parametrized sql call using JDBC", e);
        }
    }
}
